spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}  # nacos注册中心地址，集群用逗号分隔
        namespace: ${nacos.namespace}     # 命令空间
        username: ${nacos.username}   # nacos用户名
        password: ${nacos.password}   # nacos密码
        group: ${nacos.group}
        enabled: true     # 开启服务发现，默认true
        cluster-name: DEFAULT     # 把服务注册到DEFAULT集群中，默认DEFAULT
        register-enabled: true  # 把服务注册到注册中心
  #        service:         # 服务的名字，默认${spring.application.name}
  application:
    name: nacos-serviceA
server:
  port: 1000
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream