spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}  # nacos注册中心地址，集群用逗号分隔
        namespace: ${nacos.namespace}     # 命令空间
        username: ${nacos.username}   # nacos用户名
        password: ${nacos.password}   # nacos密码
        group: ${nacos.group}
        enabled: true     # 开启服务发现，默认true
#        service:         # 服务的名字，默认${spring.application.name}
  application:
    name: nacos-serviceC
server:
  port: 1100